
/datum/sprite_accessory/marking
	species_allowed = list(SPECIES_HUMAN, SPECIES_UNATHI, SPECIES_VOX, SPECIES_AKULA, SPECIES_VULP, SPECIES_VASS, SPECIES_TAJ, SPECIES_IPC, SPECIES_CUSTOM, SPECIES_OLDUNATHI, SPECIES_HUMAN2)
